[package]
name = "commit"
license = "MIT"
edition = "2021"
version = "0.0.0"
repository = "https://github.com/m1guelpf/commit"
authors = ["Miguel Piedrafita <sup@miguel.build>"]
description = "Open-source Git client for minimalists"

[dependencies]
confy = "0.5.1"
rayon = "1.7.0"
walkdir = "2.3.3"
anyhow = "1.0.72"
serde_json = "1.0"
priority-queue = "1.3.2"
window-vibrancy = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
git2 = { version = "0.17.2", default-features = false }
tauri-plugin-autostart = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }

[dependencies.tauri]
version = "1.4"
features = [
    "macos-private-api",
    "system-tray",
    "config-toml",
    "global-shortcut",
    "notification",
]

[features]
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build = { version = "1.4", features = ["config-toml"] }
